apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-java-deployment
  labels:
    app: react-java
spec:
  selector:
    matchLabels:
      app: react-java
  template:
    metadata:
      labels:
        app: react-java
    spec:
      containers:
      - name: react-java
        image: 
        ports:
        - containerPort: 8082
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: react-java
spec:
  type: LoadBalancer
  selector:
    app: react-java
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080